version: '3'

tasks:
  default:
    cmds:
    - cmd: task -l
  
  test:
    desc: |
      Run test send mail
    dir: '{{.TASKFILE_DIR}}'
    cmds:
    - go run main.go send -a leonardo_yu -m stock-info-to-self -f test-mail.yaml
  
  build:
    cmds:
    - ko build